# name: compile-blog
# run-name: Blog is compiling
# on: [push]
# jobs:
#     checkout-repo:
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v3
#             - uses: actions/setup-node@v3
#               with:
#                   node-version: "14"
#             - run: |
#                   npm install
#             - run: |
#                   node scripts/create-blog-posts/index.js
#                   git config user.name bloycey
#                   git config user.email bloyce1990@gmail.com
#                   git add .
#                   git commit -m "Auto compiled by Github Action 🤖"
#                   git push
